# Change these first
owner: lexNwimue # Your GitHub organization or username, where this repository lives
repo: inside-radio-monitor # The name of this repository

sites:
  - name: Inside Radio Homepage
    url: https://insideradiong.com
  - name: Inside Radio Admin
    url: https://insideradiong.com/customers
  - name: Inside Radio API Dashboard Metrics
    url: https://api.insideradiong.com/overview
  - name: Inside Radio API Users List
    url: https://api.insideradiong.com/users
  - name: Inside Radio API Get Users
    url: https://api.insideradiong.com/users
    expectedStatusCodes:
      - 200
      - 401
  - name: Inside Radio API Get Device Setup
    url: https://api.insideradiong.com/setup
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 401


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /inside-radio-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Inside Radio Monitor
  introTitle: "**Inside Radio** is an audio playback management solution used by malls, shops, and stores around Nigeria"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

  assignees:
    - lexNwimue
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
